version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  db:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  frontend:
       container_name: frontend
       build:
         context: ./frontend
       ports:
         - 3000:3000
       volumes:
         - ./app/src:/app/src
volumes:
  postgres_data:
